#!/bin/bash

### BEGIN INIT INFO
# Provides:          fread_startup
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: fread startup actions
# Description:       fread startup actions
### END INIT INFO
#

# Source function library.
. /lib/lsb/init-functions

start() {

    # Configure system based on config.txt file
    /opt/fread/read_config_txt.sh

    RETVAL=$?
}

case "$1" in
   start)
        start
        ;;
    stop)
        RETVAL=0
        ;;
   status)
        RETVAL=0
       ;;
   restart)
        RETVAL=0
        ;;
        *)
       echo "Usage:  {start}"
       exit 1
        ;;
esac
exit $RETVAL
